### ISSUE TITLE
Handling of missing values w.r.t. the format specifier

### ISSUE THREAD

**Issue by BambOoxX** [KlausC/Scanf.jl#8]
Hello (and thanks for this package first) !

I have to read a file which format is `(6I10)` in fortran which results in a `"%10i%10i%10i%10i%10i%10i"` here.
However, for some reason, not all the values are written in the file I target, resulting in an error. 

As an example, let's assume I have the following lines in my file
```
         1         3         2         8         5         3
         2         6         0         1
```
I can parse the first one with `@scanf(line, "%10i%10i%10i%10i%10i%10i", Int64, Int64, Int64, Int64, Int64, Int64)` which returns `(6,1,3,2,8,5,3)`, but if I parse the second one with the same instruction, I get a 
> BoundsError: attempt to access Tuple{IOBuffer, Bool} at index [3]

while I would have expected something like a `(4,2,6,0,1,missing,missing)`.

Any ideas how to avoid that error ?

**Comment by KlausC** [comment]
There are a few comments.

1. Thanks for revealing a bug in the package.  I will fix that. There should be no `BoundsError`, but default values for the missing data should returned. (They would be `zero(Int64)` in your case; it is not possible to return `Union{Int64, Missing}`)
2. The scanf formats are following the `C++` standard, which differs essentially from `Fortran` formats. See link in `readme`
3. `I10` would be closer to `%10d`, but not exactly
4. `%10d` would first skip any amount of whitespace (including newlines), then consume up to 10 decimal digits (and optional sign)
5. The mimic the Fortran behavior, you could read line by line, then split the line into strings of length 10 ("%10c"), then parse the strings individually.

Code example corresponding to Fortran format "I2I2I2I2"
```
julia> line = " 1 234"
" 1 234"

julia> r, a... = @scanf(s, "%2c%2c%2c%2c", fill(String, 4)...)
(3, " 1", " 2", "34", "")

julia> [x[1] == 1 ? x[2] : missing for x in scanf.(a, Ref(Scanf.format"%d"), -77)]
4-element Vector{Union{Missing, Int64}}:
  1
  2
 34
   missing

**Comment by KlausC** [comment]
@JuliaRegistrator register
v0.5.1

**Comment by BambOoxX** [comment]
Thanks for the fix.

I think I don't get the difference between the ways integers are parsed between fortran and cpp, but the current implementation works just fine for my application.

**Comment by KlausC** [comment]
If your input is `" 987"`, then `scanf(%2d%2d", Int, Int)` returns `(2, 98, 7)` while Fortran read with format `"I2I2"` gives `9, 87`

**Comment by BambOoxX** [comment]
OK. Thanks for the precision. Do you think it would be relevant to add a set of fortrans specifiers? e.g. with capital letters?
