### ISSUE TITLE
possible error with specifier %c

### ISSUE THREAD

**Issue by songjhaha** [KlausC/Scanf.jl#9]
Hi! 
Thanks for this package. It help me learn a lot.

I get some unexpected output when parsing with specifier %c:
```
julia> f = Scanf.Format("%c")
Scanf.format"%c"

julia> scanf("abcd",f,"")
(1, "abcd")
```

I think the correct outputs should only parsing one char, but get whole sentence.

maybe the problem is from here, where `S` is a `Spec{Chars}` so `S <: Chars` is `false`.
https://github.com/KlausC/Scanf.jl/blob/5f61c1d74a41807bd5598bcf313b7524b95a3bb9/src/Scanf.jl#L344

**Comment by KlausC** [comment]
You are completely right. I fixed that
@juliaregistrator register

**Comment by KlausC** [comment]
@JuliaRegistrator register
